version: '3.8'

services:
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: my-dynamodb
    restart: always
    user: root
    volumes:
      -  ./my-dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    
volumes:
  dynamodblocal: null

networks:
  default:
    name: userService
    driver: bridge
