AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 128
    Architectures: ["arm64"]
    Handler: bootstrap
    Runtime: provided.al2
    Timeout: 25
    Tracing: Active
    Environment:
      Variables:
        DYNAMO_TABLE_NAME: users

Resources:
  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/authorizer/
      Role: arn:aws:iam::227833266304:role/user-invoice
      
  SignInFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/signin/
      Role: arn:aws:iam::227833266304:role/user-invoice


  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/signup/
      Role: arn:aws:iam::227833266304:role/user-invoice
